// SPDX-License-Identifier: AGPL-3.0-or-later
import {DEFAULT_THEME, freshProject, parseImport, normalizeViewport, safeImageUrl, avatarRule, themeForExport} from './core.mjs';
const $=id=>document.getElementById(id), editor=$('css-editor'), frame=$('preview');
let project=freshProject(), channel='',ready=false,renderTimer,saveTimer,toastTimer,history=[],historyIndex=-1,historyTimer,inspection=false,selector='',template='',db=null,assetOffset=0,assetAlbum='',assetRequest=0;
const base=new URL('./',import.meta.url).href;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function clone(x){return structuredClone(x)}
function snapshot(){project.theme=themeForExport(project.theme,$('theme-name').value,editor.value);return clone(project)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('qiuqiu-workshop',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function draftRequest(mode,value){return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode),store=tx.objectStore('drafts');const r=mode==='readonly'?store.get('current'):store.put(value,'current');tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存被中断'))})}
async function saveDraft(silent=false){clearTimeout(saveTimer);const data=snapshot();try{if(!db)throw new Error('存储不可用');await draftRequest('readwrite',data);$('save-state').textContent='已保存到本机 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});if(!silent)toast('草稿已保存到当前浏览器')}catch{$('save-state').textContent='本机保存失败，请备份工程';if(!silent)toast('浏览器存储不可用或空间不足，请点击“备份工程”。')}}
function changed(){project.theme.custom_css=editor.value;project.theme.name=$('theme-name').value;$('save-state').textContent='有更改 · 即将保存';clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft(true),600);clearTimeout(renderTimer);renderTimer=setTimeout(render,160);updateLines()}
function send(type,data={}){if(ready)frame.contentWindow.postMessage({channel,type,...data},'*')}
function render(){send('render',{theme:{...DEFAULT_THEME,...project.theme,custom_css:editor.value},sample:project.sample})}
function updateLines(){const n=editor.value.split('\n').length;$('line-count').textContent=n+' 行';$('line-numbers').textContent=Array.from({length:n},(_,i)=>i+1).join('\n');$('line-numbers').scrollTop=editor.scrollTop}
function record(){clearTimeout(historyTimer);if(history[historyIndex]===editor.value)return;history=history.slice(0,historyIndex+1);history.push(editor.value);if(history.length>40)history.shift();historyIndex=history.length-1;historyButtons()}
function historyButtons(){$('undo').disabled=historyIndex<=0;$('redo').disabled=historyIndex>=history.length-1}
function setCss(css){record();editor.value=css;record();changed()}
function moveHistory(delta){record();const next=historyIndex+delta;if(next<0||next>=history.length)return;historyIndex=next;editor.value=history[next];historyButtons();changed()}
function insertCss(text){const start=editor.selectionStart,end=editor.selectionEnd;setCss(editor.value.slice(0,start)+text+editor.value.slice(end));editor.focus();editor.setSelectionRange(start+text.length,start+text.length)}
function colorHex(value,fallback){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.fillStyle=fallback;if(typeof value==='string'&&CSS.supports('color',value))ctx.fillStyle=value;const c=ctx.fillStyle;if(/^#[0-9a-f]{6}$/i.test(c))return c;const nums=c.match(/[\d.]+/g);return nums?.length>=3?'#'+nums.slice(0,3).map(n=>Math.round(+n).toString(16).padStart(2,'0')).join(''):fallback}
function syncControls(){const t={...DEFAULT_THEME,...project.theme},s=project.sample;$('theme-name').value=t.name||'我的酒馆美化';editor.value=t.custom_css||'';$('chat-display').value=String(t.chat_display);$('avatar-style').value=String(t.avatar_style);$('font-scale').value=t.font_scale;$('font-scale-value').value=t.font_scale;$('chat-width').value=t.chat_width;$('chat-width-value').value=t.chat_width+'%';$('main-color').value=colorHex(t.main_text_color,'#dcdcd2');$('em-color').value=colorHex(t.italics_text_color,'#919191');for(const [id,key] of Object.entries(sampleFields))$(id).value=s[key]||'';$('message-count').value=s.count;$('show-meta').checked=t.mesIDDisplay_enabled!==false;$('show-time').checked=t.timestamps_enabled!==false;$('show-actions').checked=!!t.expand_message_actions;$('generating').checked=!!s.generating;project.viewport=normalizeViewport(project.viewport);$('vp-width').value=project.viewport.width;$('vp-height').value=project.viewport.height;$('zoom').value=project.viewport.zoom;syncDevice();updateLines();history=[];historyIndex=-1;record();resizePreview();render()}
const sampleFields={'user-name':'userName','char-name':'charName','user-text':'userText','char-text':'charText','user-avatar':'userAvatar','char-avatar':'charAvatar','background-url':'background'};
function syncDevice(){const val=project.viewport.width+','+project.viewport.height;$('device').value=[...$('device').options].some(o=>o.value===val)?val:'custom'}
function resizePreview(){const {width,height,zoom}=project.viewport;frame.width=width;frame.height=height;frame.style.width=width+'px';frame.style.height=height+'px';const stage=$('stage'),availableW=stage.clientWidth-48,availableH=stage.clientHeight-40;let scale=zoom==='fit'?Math.min(1,Math.max(0.08,availableW/width),Math.max(.08,availableH/height)):+zoom;if(!Number.isFinite(scale))scale=1;$('frame-wrap').style.width=width+'px';$('frame-wrap').style.height=height+'px';$('frame-wrap').style.transform=`scale(${scale})`;$('frame-space').style.width=width*scale+'px';$('frame-space').style.height=height*scale+'px';$('viewport-label').textContent=`${width} × ${height} · ${Math.round(scale*100)}%`}
async function bootPreview(){ready=false;$('render-state').textContent='正在加载酒馆界面…';try{if(!template){const r=await fetch(new URL('frame.html',base));if(!r.ok)throw new Error('预览资源 '+r.status);template=await r.text()}channel=crypto.randomUUID();const nonce=crypto.randomUUID().replaceAll('-','');frame.srcdoc=template.replaceAll('__BASE__',base.replaceAll('&','&amp;').replaceAll('"','&quot;')).replaceAll('__CHANNEL__',channel).replaceAll('__NONCE__',nonce)}catch(e){$('render-state').textContent='预览加载失败';toast(e.message+'。请确认整个 workshop 文件夹已上传。')}}
window.addEventListener('message',event=>{const d=event.data;if(event.source!==frame.contentWindow||d?.channel!==channel||d.source!=='qiuqiu-preview')return;if(d.type==='ready'){ready=true;render();send('inspect',{enabled:inspection})}if(d.type==='rendered')$('render-state').textContent='已应用 · '+d.width+' × '+d.height;if(d.type==='viewport')$('render-state').textContent='当前界面 · '+d.width+' × '+d.height;if(d.type==='warning'||d.type==='error')toast(d.message);if(d.type==='selected'){selector=String(d.selector);$('selected-selector').textContent=selector;inspection=false;$('inspect').classList.remove('active');send('inspect',{enabled:false});toast('已选中，可点“插入 CSS”开始修改')}});
editor.addEventListener('input',()=>{changed();clearTimeout(historyTimer);historyTimer=setTimeout(record,500)});editor.addEventListener('scroll',()=>$('line-numbers').scrollTop=editor.scrollTop);editor.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();insertCss('  ')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();moveHistory(e.shiftKey?1:-1)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();moveHistory(1)}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveDraft()}});
$('theme-name').addEventListener('input',changed);$('undo').onclick=()=>moveHistory(-1);$('redo').onclick=()=>moveHistory(1);$('save-draft').onclick=()=>saveDraft();
$('device').onchange=()=>{if($('device').value!=='custom'){const [width,height]=$('device').value.split(',').map(Number);project.viewport={...project.viewport,width,height};$('vp-width').value=width;$('vp-height').value=height;resizePreview();changed()}};
for(const id of ['vp-width','vp-height'])$(id).addEventListener('change',()=>{project.viewport=normalizeViewport({width:$('vp-width').value,height:$('vp-height').value,zoom:$('zoom').value});$('vp-width').value=project.viewport.width;$('vp-height').value=project.viewport.height;syncDevice();resizePreview();changed()});$('rotate').onclick=()=>{project.viewport=normalizeViewport({...project.viewport,width:project.viewport.height,height:project.viewport.width});$('vp-width').value=project.viewport.width;$('vp-height').value=project.viewport.height;syncDevice();resizePreview();changed()};$('zoom').onchange=()=>{project.viewport.zoom=$('zoom').value;resizePreview();changed()};new ResizeObserver(resizePreview).observe($('stage'));
for(const [id,key] of [['chat-display','chat_display'],['avatar-style','avatar_style'],['font-scale','font_scale'],['chat-width','chat_width']])$(id).addEventListener('input',()=>{project.theme[key]=+$(id).value;if(id==='font-scale')$('font-scale-value').value=$(id).value;if(id==='chat-width')$('chat-width-value').value=$(id).value+'%';changed()});for(const [id,key] of [['main-color','main_text_color'],['em-color','italics_text_color']])$(id).oninput=()=>{project.theme[key]=$(id).value;changed()};
for(const [id,key] of Object.entries(sampleFields))$(id).addEventListener('input',()=>{project.sample[key]=$(id).value;changed()});$('message-count').onchange=()=>{project.sample.count=+$('message-count').value;changed()};$('show-meta').onchange=()=>{for(const k of ['mesIDDisplay_enabled','timer_enabled','message_token_count_enabled'])project.theme[k]=$('show-meta').checked;changed()};$('show-time').onchange=()=>{project.theme.timestamps_enabled=$('show-time').checked;changed()};$('show-actions').onchange=()=>{project.theme.expand_message_actions=$('show-actions').checked;changed()};$('generating').onchange=()=>{project.sample.generating=$('generating').checked;changed()};
$('apply-avatar').onclick=()=>setCss(avatarRule(editor.value,$('avatar-target').value,{size:$('avatar-size').value,radius:$('avatar-radius').value,x:$('avatar-x').value,y:$('avatar-y').value}));$('remove-avatar').onclick=()=>setCss(avatarRule(editor.value,$('avatar-target').value,{},true));
$('inspect').onclick=()=>{inspection=!inspection;$('inspect').classList.toggle('active',inspection);send('inspect',{enabled:inspection})};$('insert-selector').onclick=()=>{if(!selector)return toast('请先点“点选元素”，再点击预览中的元素。');insertCss('\n'+selector+' {\n  \n}\n');switchView('code')};$('reset-preview').onclick=bootPreview;
function switchView(view){document.querySelector('.workspace').dataset.view=view;document.querySelectorAll('.mobile-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));requestAnimationFrame(resizePreview)}document.querySelectorAll('.mobile-tabs button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('focus-preview').onclick=()=>{const expanded=document.body.classList.toggle('preview-focus');$('focus-preview').textContent=expanded?'↙ 返回编辑':'⛶ 展开';requestAnimationFrame(resizePreview)};
function download(contents,name,type){const blob=new Blob([contents],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}function filename(){return ($('theme-name').value.trim()||'我的酒馆美化').replace(/[\\/:*?"<>|\x00-\x1f]/g,'_')}
$('export-theme').onclick=()=>{const p=snapshot();download(JSON.stringify(p.theme,null,2)+'\n',filename()+'.json','application/json');toast('已导出主题 JSON，可导入酒馆。')};$('export-css').onclick=()=>download(editor.value,filename()+'.css','text/css');$('export-project').onclick=()=>download(JSON.stringify(snapshot(),null,2),filename()+'.workshop.json','application/json');$('copy-css').onclick=async()=>{try{await navigator.clipboard.writeText(editor.value);toast('CSS 已复制')}catch{editor.focus();editor.select();toast('自动复制不可用，已选中代码，请手动复制。')}};
$('import-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=parseImport(await file.text(),file.name);if(parsed.type==='css'){setCss(parsed.css)}else{if(parsed.type==='project')project=parsed.project;else project.theme=parsed.theme;syncControls();changed()}toast(parsed.type==='project'?'工程已恢复':'导入完成，已更新预览')}catch(err){toast(err.message)}finally{e.target.value=''}};
$('new-project').onclick=()=>$('confirm-dialog').showModal();$('confirm-dialog').addEventListener('close',()=>{if($('confirm-dialog').returnValue==='create'){project=freshProject();syncControls();changed();toast('已新建美化')}});
const snippets={avatar:'\n/* 角色头像 */\n#chat .mes[is_user="false"] .avatar,\n#chat .mes[is_user="false"] .avatar img {\n  width: 70px;\n  height: 70px;\n  object-fit: cover;\n}\n',bubble:'\n#chat .mes[is_user="true"] {\n  background: #dceff366;\n}\n#chat .mes[is_user="false"] {\n  background: #f5dce466;\n}\n',text:'\n#chat .mes_text { color: #343434; }\n#chat .mes_text em { color: #e59aaf; }\n#chat .mes_text u { color: #75bfcf; }\n',mobile:'\n@media (max-width: 600px) {\n  #chat .mes_text { font-size: 15px; }\n}\n',background:'\n#chat .mes[is_user="false"] {\n  background-image: url("在这里填写图片链接");\n  background-size: 100% 100%;\n  background-repeat: no-repeat;\n}\n'};$('snippet').onchange=()=>{if(snippets[$('snippet').value])insertCss(snippets[$('snippet').value]);$('snippet').value=''};
async function api(path){const r=await fetch('/api/studio/'+path,{credentials:'same-origin'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||(r.status===401?'请先回甜品屋登录，再读取相册。':'相册读取失败'));return data}
$('load-albums').onclick=async()=>{$('load-albums').disabled=true;try{const data=await api('albums');$('album-list').replaceChildren(new Option('选择相册',''));for(const a of data.albums||[])$('album-list').append(new Option(a.name,a.id));$('asset-status').textContent='选择相册后，点击图片即可使用。'}catch(e){$('asset-status').textContent=e.message}finally{$('load-albums').disabled=false}};
async function loadAssets(more=false){const album=$('album-list').value;if(!album)return;const request=++assetRequest;if(!more){assetOffset=0;assetAlbum=album;$('asset-grid').replaceChildren()}const offset=assetOffset;$('more-assets').disabled=true;try{const data=await api(`files?album=${encodeURIComponent(album)}&offset=${offset}`);if(request!==assetRequest||album!==assetAlbum)return;for(const f of data.files||[]){const url=safeImageUrl(f.url);if(!url||(/\.(woff2?|ttf|otf)(\?|$)/i.test(url)))continue;const b=document.createElement('button'),img=new Image();b.type='button';b.title=f.name||'使用图片';img.src=url;img.alt=f.name||'相册图片';img.loading='lazy';img.referrerPolicy='no-referrer';b.append(img);b.onclick=()=>useAsset(url);$('asset-grid').append(b)}assetOffset=offset+(data.files||[]).length;$('more-assets').hidden=!data.hasMore;$('asset-status').textContent='点击图片应用到所选用途。'}catch(e){$('asset-status').textContent=e.message}finally{$('more-assets').disabled=false}}
$('album-list').onchange=()=>loadAssets();$('more-assets').onclick=()=>loadAssets(true);
function useAsset(raw){const url=safeImageUrl(raw);if(!url)return toast('图片地址不可用，请使用 http(s) 图链。');const key=$('asset-target').value;if(key==='css'){insertCss('\n/* 图片素材 */\n#chat .mes[is_user="false"] {\n  background-image: url('+JSON.stringify(url)+');\n  background-size: cover;\n}\n');toast('图片链接已插入 CSS')}else{project.sample[key]=url;const field=Object.entries(sampleFields).find(([,k])=>k===key)?.[0];if(field)$(field).value=url;changed();toast('预览素材已更新')}}
$('asset-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(!/^image\/(png|jpeg|gif|webp|avif|bmp)$/.test(f.type))throw new Error('请选择 PNG、JPG、GIF、WebP、AVIF 或 BMP 图片。');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(f)});useAsset(data)}catch(err){toast(err.message||'图片读取失败')}finally{e.target.value=''}};
window.addEventListener('pagehide',()=>{if(db)saveDraft(true)});
try{db=await openDB();const draft=await draftRequest('readonly');if(draft){project=parseImport(JSON.stringify(draft),'draft.json').project;$('save-state').textContent='已恢复本机草稿'}else $('save-state').textContent='新作品 · 自动保存到本机'}catch{$('save-state').textContent='本机存储不可用，请备份工程'}syncControls();await bootPreview();
