// SPDX-License-Identifier: AGPL-3.0-or-later
import {SELECTORS} from './selector-catalog.mjs?v=20261005a';
export function initInspectorUI({$,send,search,switchView,insertCss,toast,chooseScene,onSelector}) {
  let selection=null,catalogVersion=0,shown=[],catalogButtons=new Map();
  const styleNames={'display':'显示方式','position':'定位方式','width':'宽度','height':'高度','margin':'外边距','padding':'内边距','z-index':'层级','font-size':'字号','color':'文字颜色','background-color':'背景色','overflow':'溢出','transform':'变换','content':'装饰内容'};
  function selected(data){for(const id of ['inspect-nodes','inspect-scope','inspect-pseudo'])$(id).disabled=false;selection=data;onSelector(data.selector);$('inspect-selector').textContent=data.selector;const old=$('inspect-nodes').value;$('inspect-nodes').replaceChildren();for(const n of data.nodes||[])$('inspect-nodes').append(new Option(n.label,n.id));$('inspect-nodes').value=data.nodeId||old;$('inspect-scope').value=data.scope||'role';$('inspect-pseudo').value=data.pseudo||'';const state=data.visible?(data.pseudo&&!data.generated?'装饰层未生成（content 为 none / normal）':'当前可见'):'节点已挂载，但当前未显示';$('inspect-info').textContent=`${data.count} 处匹配 · ${state} · ${data.size||''}`;$('inspect-styles').replaceChildren();for(const [key,value] of Object.entries(data.computed||{})){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=styleNames[key]||key;dd.textContent=value||'—';$('inspect-styles').append(dt,dd)}}
  function missing(selector){for(const id of ['inspect-nodes','inspect-scope','inspect-pseudo'])$(id).disabled=true;selection={selector,searchToken:selector};onSelector(selector);$('inspect-selector').textContent=selector;$('inspect-nodes').replaceChildren(new Option('此节点未挂载到预览',''));$('inspect-styles').replaceChildren();$('inspect-info').textContent='官方源码中有此选择器，当前预览未挂载对应节点；仍可查找或插入 CSS。'}
  function find(){if(!selection)return toast('请先点选元素，或从元素速查中选择。');search.open(selection.searchToken||selection.selector);toast('正在查找 '+(selection.searchToken||selection.selector)+'；支持不同写法的选择器逐处查看。')}
  function insert(){if(!selection)return toast('请先选择一个元素。');insertCss('\n'+selection.selector+' {\n  \n}\n');switchView('code')}
  function show(){switchView('settings');$('inspector-panel').open=true;$('inspector-panel').scrollIntoView({block:'nearest'})}
  $('inspect-nodes').onchange=()=>send('inspect-node',{id:$('inspect-nodes').value});for(const id of ['inspect-scope','inspect-pseudo'])$(id).onchange=()=>send('inspect-options',{scope:$('inspect-scope').value,pseudo:$('inspect-pseudo').value});
  $('find-selected-css').onclick=find;$('insert-selected-css').onclick=insert;$('find-selector').onclick=find;$('show-inspector').onclick=show;
  function catalog(){const query=$('catalog-search').value.trim().toLowerCase();const matched=SELECTORS.filter(x=>query?(x.label+' '+x.selector+' '+x.category).toLowerCase().includes(query):x.common);shown=matched.slice(0,80);catalogVersion++;catalogButtons=new Map();$('selector-catalog').replaceChildren();const hint=document.createElement('p');hint.className='hint';hint.textContent=(query?'匹配 '+matched.length+' 项':'常用 '+matched.length+' 项 · 可搜索 '+SELECTORS.length+' 个官方选择器')+(matched.length>80?'，先显示前 80 项，请继续缩小搜索范围。':'');$('selector-catalog').append(hint);for(const entry of shown){const button=document.createElement('button'),label=document.createElement('span'),code=document.createElement('code'),status=document.createElement('small');button.type='button';label.textContent=entry.category+' · '+entry.label;code.textContent=entry.selector;status.textContent='检查中';button.append(label,code,status);button.onclick=()=>{if(entry.selector==='#preloader')chooseScene('preloader');if(['#loader','#load-spinner'].includes(entry.selector))chooseScene('loader');send('inspect-query',{selector:entry.selector});show()};$('selector-catalog').append(button);catalogButtons.set(entry.selector,status)}requestStatus()}
  function requestStatus(){send('catalog-query',{version:catalogVersion,selectors:shown.map(x=>x.selector)})}
  function status(data){if(data.version!==catalogVersion)return;for(const row of data.rows||[]){const el=catalogButtons.get(row.selector);if(el)el.textContent=row.count?row.visible?' · '+row.count+' 处，可见':' · 已挂载，未显示':' · 未挂载'}}
  $('catalog-search').oninput=catalog;$('catalog-panel').addEventListener('toggle',()=>{if($('catalog-panel').open)requestStatus()});catalog();
  return {selected,missing,status,requestStatus};
}
